-- H2-compatible V10: Create push_subscriptions table
-- H2 does not support all PostgreSQL-specific DDL, but this table uses only
-- standard SQL compatible with both H2 (in PostgreSQL mode) and PostgreSQL.

CREATE TABLE push_subscriptions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    endpoint    TEXT NOT NULL,
    auth_key    TEXT NOT NULL,
    p256dh_key  TEXT NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_push_subscriptions_endpoint UNIQUE (endpoint)
);

CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions (user_id);
