-- H2-compatible V12: Create user_cleanup_settings table
-- H2 does not support CHECK constraints with IN lists in the same syntax as PostgreSQL.
-- The allowed-values constraint is enforced at the application layer instead.

CREATE TABLE user_cleanup_settings (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    staleness_threshold_days  INT NOT NULL DEFAULT 30,
    auto_cleanup_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_cleanup_settings_user UNIQUE (user_id)
);

CREATE INDEX idx_user_cleanup_settings_user_id ON user_cleanup_settings (user_id);
