-- H2-compatible V4: Create items table
-- H2 does not support PostgreSQL ENUM types, TSVECTOR, or trigger-based tsvector updates.
-- item_type uses VARCHAR, search_vector uses VARCHAR (not used in tests).
CREATE TABLE items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id     BIGINT REFERENCES categories (id) ON DELETE SET NULL,
    item_type       VARCHAR(10) NOT NULL,
    url             VARCHAR(2048),
    title           VARCHAR(1000),
    favicon_url     VARCHAR(2048),
    summary         CLOB,
    note_body       CLOB,
    is_pinned       BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived     BOOLEAN NOT NULL DEFAULT FALSE,
    last_visited_at TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    search_vector   VARCHAR(4000)
);

CREATE INDEX idx_items_user_id ON items (user_id);
CREATE INDEX idx_items_category_id ON items (category_id);
