-- H2-compatible V5: Create content_analysis_jobs table
-- H2 does not support PostgreSQL ENUM types.
-- status uses VARCHAR instead.
CREATE TABLE content_analysis_jobs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id           BIGINT NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count       INT NOT NULL DEFAULT 0,
    last_attempted_at TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_content_analysis_jobs_item_id ON content_analysis_jobs (item_id);
CREATE INDEX idx_content_analysis_jobs_status ON content_analysis_jobs (status);
