-- H2-compatible V6: Create suggested_reminders table
-- H2 does not support PostgreSQL custom ENUM types.
-- urgency and status use VARCHAR instead.

CREATE TABLE suggested_reminders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         BIGINT NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    detected_date   DATE NOT NULL,
    label           VARCHAR(500) NOT NULL,
    urgency         VARCHAR(20) NOT NULL DEFAULT 'medium',
    status          VARCHAR(30) NOT NULL DEFAULT 'pending_confirmation',
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_suggested_reminders_item_id ON suggested_reminders (item_id);
CREATE INDEX idx_suggested_reminders_user_id ON suggested_reminders (user_id);
CREATE INDEX idx_suggested_reminders_status  ON suggested_reminders (status);
